### PR TITLE
Fix package name and version in composer.json

### PR DESCRIPTION
**Pull request by rafis**
Also need to add tag "0.1" to [goetas-webservices/wsdl-reader](https://github.com/goetas-webservices/wsdl-reader).

### CODE REVIEW

**Comment by goetas** [comment]
I'm moving all packages to `goetas-webserices`. The `goetas` and `goetas-webserices` packages are not compatible. 

`goetas-webserices` should be available in a couple of months.

**Comment by rafis** [comment]
Yes, I have also discovered that they are incompatible.

Can you recover [goetas/wsdl-reader](https://packagist.org/packages/goetas/wsdl-reader) then? It is referred by composer packagist [goetas/wsdl-reader](https://packagist.org/packages/goetas/wsdl-reader).

**Comment by goetas** [comment]
@rafis Ah, now u understand. My fault. I will do it in the next couple of days.

**Comment by goetas** [comment]
@rafis hi! can you try again?

**Comment by rafis** [comment]
Yes, thank you. Composer install is working now. But it still doesn't satisfies my needs, I don't remember that exactly was unsatisfactory. Before that I was trying to use native SoapServer, but it was telling "error parsing WSDL" or something like that, through native SoapClient successfully parses this WSDL!  I can't debug native SoapServer written C, because it is too hard, and I think PHP core developer which developed SoapServer are wrong - it is an evil of all evils, developing such high level feature as Soap Server (Ethernet - TCP - HTTP - XML - Soap - WSDL) must not happen on such low level language as C. Soap Server written on PHP would be still faster than Microsoft's Soap Server. So I decided to use yours, but it still not ready. After some fighting I have surrendered, and have switched to pure XML processing using SimpleXML and PEAR XML_Serializer. And it worked!

Some suggestions:
1. Try to design interface (API) as close as possible to SoapServer through it is poorly documented :(
2. Good practice is to developed with strict mode enabled error_reporting=E_ALL.

**Pull request closed without merging**
